---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}-app
  labels:
    app: {{APP_NAME}}-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{APP_NAME}}-app
  template:
    metadata:
      labels:
        app: {{APP_NAME}}-app
        commitHash: "{{COMMIT_SHA}}"
        buildNumber: "{{BUILD_NUMBER}}"
    spec:
      dnsConfig:
        options:
          - name: single-request
      imagePullSecrets:
        - name: registry.dak.dev
      containers:
        - name: server
          image: {{DOCKER_REGISTRY_URL}}/{{DOCKER_IMAGE_NAME}}:{{COMMIT_SHA}}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: AWS_REGION
              value: "{{AWS_REGION}}"
            - name: APP_COMMIT_SHA
              value: "{{COMMIT_SHA}}"
          envFrom:
            - secretRef:
                name: "{{APP_NAME}}-{{VCS_BRANCH}}-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}-service
spec:
  ports:
    - port: 4000
      name: web
      targetPort: 4000
  selector:
    app: {{APP_NAME}}-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{APP_NAME}}-ingress
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - {{APP_HOSTNAME}}
  rules:
    - host: {{APP_HOSTNAME}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{APP_NAME}}-service
              servicePort: 4000
